# Generated by Django 4.1.1 on 2022-10-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('price', models.FloatField(verbose_name='Price')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('librero', models.CharField(max_length=50, verbose_name='Librero')),
                ('rating', models.CharField(max_length=10, verbose_name='Rating')),
                ('comment', models.CharField(max_length=500, verbose_name='Comment')),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
