# Generated by Django 4.1.1 on 2022-11-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='None', max_length=120, verbose_name='Full name'),
        ),
    ]
